feat: ensure all gateways active in XDNS on XTX validate, revert, confirm attempts
t3rn/t3rn pull request #1058
Opened 2023-06-14 09:32 UTC by MaciejBaj

# Summary of changes

**_Summarize_** the description of your changes.

If it fixes a bug or creates a feature, link the issue.

# Acceptance Checklist

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

## Dependencies

- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any teams which manage the dependencies have been notified of the breaking changes

## Bug (non-breaking change which fixes an issue):

- [ ] Have you **_written tests_** to protect against future occurrences of the bug?

## Feature (non-breaking change which adds functionality)

- [ ] Have you **_seen it working_** in a development environment?
- [ ] Have you **_written tests_** for **_happy_** and **_unhappy_** paths?
- [ ] Have you implemented this feature as per the **_issue acceptance criteria_**?

### Substrate

If this change involves substrate, have you remembered:

- [ ] Storage Migration?
- [ ] RPC methods?
- [ ] Chainspec, both JSON specs & the module?
- [ ] Runtime versioning?
- [ ] Benchmarks?

## Breaking change (a feature that would cause existing functionality not to work as expected)

- [ ] Is the breaking change **_documented_**?
- [ ] Are your commits fully representative of the change?
- [ ] Has any previous functionality been **_deprecated_** and versioned?

## CI/CD

- [ ] If introducing new actions, have you **_looked at the action code_** for anything spurious?
- [ ] Have you written **_custom scripts_** for things that could be actions already on the marketplace?
- [ ] If introducing new actions, have you **_pegged a static version_**?

## Documentation Update

- [ ] Have you checked other documentation, such as the docs repository?
- [ ] If updating script documentation, have you **_tested it on both environments_**?

## Further comments

Feel free to explain in further detail your choices if this is a significant change.

## Screenshots (Please demonstrate this working in PolkadotJS)

2023-06-14 09:38 UTC, AwesomeIbex commented on pallets/circuit/src/lib.rs
> +            if gateway_activity_overview.is_active {
This is a bug here, should be `!is_active` to comply with this message

2023-06-14 09:39 UTC, AwesomeIbex commented on pallets/circuit/src/lib.rs
> +            }
I think this can be reduced to `<T as Config>::Xdns::read_last_activity(..).map(|x| x.is_active).ok_or(false)` and then log on the falsy value.

2023-06-14 09:42 UTC, AwesomeIbex commented on pallets/circuit/src/lib.rs
> +        }
Im not sure this weight number is correct, since you make a read for each gateway check

2023-06-14 09:43 UTC, AwesomeIbex commented on pallets/circuit/src/lib.rs
> +            }
Same here, this code shouldnt be duplicate of the one below either

2023-06-14 09:44 UTC, AwesomeIbex requested changes
Slight logic bug & Optimisations

2023-06-14 09:52 UTC, AwesomeIbex commented
This is good as a first pass; however, failing fast likely is an issue since we trust that the executor will try to recover the failed TX again. IMO, the best approach to these failing confirmations and reverts need to be posted to a dead letter queue to rehandle the message in the future for a full "recovery" since right now we just trust the user to try to resend the message.

See

https://en.wikipedia.org/wiki/Dead_letter_queue

https://en.wikipedia.org/wiki/Fault_tolerance

2023-07-12 11:28 UTC, MaciejBaj commented
succeed by #345

2023-07-12 11:28 UTC, closed without merging