Convert Circuit into a Parachain
t3rn/t3rn pull request #169
Opened 2021-11-10 14:56 UTC by beqaabu

Closes #158

2021-11-11 11:08 UTC, vedhavyas commented on circuit-parachain/node/Cargo.toml
> +name = "parachain-template-node"
lets rename this

2021-11-12 09:13 UTC, beqaabu commented on circuit-parachain/node/Cargo.toml
> +name = "parachain-template-node"
updated on the following commit

2021-11-12 09:25 UTC, MaciejBaj requested changes
also, remove `pallet-template` from Cargo + Cargo.lock

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/.dockerignore
> +/.*
missing EOF line - correct in other files too

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/node/src/command.rs
> +	service::{new_partial, TemplateRuntimeExecutor},
Rename `TemplateRuntimeExecutor` -> `CircuitRuntimeExecutor`

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/node/Cargo.toml
> +repository = 'https://github.com/substrate-developer-hub/substrate-parachain-template'
change desc - apply consistently

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/node/Cargo.toml
> +license = "Unlicense"
Apache 2.0 - apply consistently

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/node/src/command.rs
> +		"Parachain Collator Template".into()
Change from Template to Circuit in command.rs consistently

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/node/src/chain_spec.rs
> +						template_session_keys(aura), // session keys
change template naming in chain_spec

2021-11-12 09:25 UTC, MaciejBaj commented on circuit-parachain/node/src/command.rs
> +		"template-rococo" => Box::new(chain_spec::local_testnet_config(para_id)),
@vedhavyas fetch spec for testnet from remote url?

2021-11-12 11:33 UTC, closed without merging