Adds ranger recovery logic
t3rn/t3rn pull request #384
Opened 2022-07-05 14:53 UTC by petscheit

## Summary
The grandpa ranger was missing authority set update detection. This is important in two scenarios:

### While running:
While the ranger is running, it must be ensured justifications containing an authority update are submitted to the circuit. With this PR, every incoming header is checked for an authority set update, and submitted to the circuit if needed.

### On start:
Before starting the listeners, the ranger now checks for any missed justifications containing an authority update. These are then submitted to the circuit, ensuring the following justifications can be submitted.

closes #243 #283

(and I had to change to tab indentions, as this space stuff was making me go insane. Sorry.)

2022-07-06 10:36 UTC, petscheit commented on client/grandpa-ranger/src/util.ts
> +}
very inefficient way of checking if a justification contains an authority set update

2022-07-06 10:37 UTC, petscheit commented
Sorry about the mess with the indentions. I have commented on the important bits.

2022-07-12 11:29 UTC, chiefbiiko submitted a review, later dismissed
SUPER SAUCY !!!

2022-07-12 11:29 UTC, chiefbiiko commented on client/grandpa-ranger/package.json
> +    "axios": "^0.27.2",
```suggestion
    "axios": "=0.27.2",
```
developed dis auto update paranoia..would go for a pinned npm version

2022-07-12 18:13 UTC, MaciejBaj commented on client/grandpa-ranger/src/index.ts
> +            const _relaychainParams: {
remove underscore since the const is used later

2022-07-12 18:18 UTC, MaciejBaj commented on client/grandpa-ranger/src/relayer.ts
> +                    Relayer.debug("FinalityProofSubmitted failed")
no try error to redo?

2022-07-12 18:23 UTC, MaciejBaj requested changes

2022-07-12 18:23 UTC, MaciejBaj commented on pallets/circuit-portal/rpc/src/types.rs
> +// ToDo: the types where not implemented consistently. We need to figure out how to handle RPC in general, currently its handled differently in contracts and RPC.
not a fan of commenting out. just remove if unused

2022-10-27 10:14 UTC, closed without merging