srtool hotfix specifying image
t3rn/t3rn pull request #386
Opened 2022-07-06 13:09 UTC by phpengine

## Summary
Change report commands to specify a custom image, tagged as 

## Checklist
One line change to flag calling command

2022-07-06 14:27 UTC, chiefbiiko requested changes
Some small cosmetics only

2022-07-06 14:27 UTC, chiefbiiko commented on scripts/upgrade-runtime.sh
> +    --image t3rn-srtool:1.60.0 \
```suggestion
    --image t3rn/srtool:1.60.0 \
```

2022-07-06 14:27 UTC, chiefbiiko commented on scripts/upgrade-runtime.sh
> +echo "compiler prerequisites"
```suggestion
echo "🐳 monkey patching srtool-cli..."
```

2022-07-06 15:36 UTC, phpengine commented on scripts/upgrade-runtime.sh
> +docker tag $( docker image ls | grep 1.57.0 | awk '{ print $3 }' ) t3rn-srtool:1.60.0
Correct on both points, adding and repushing these now

2022-07-06 15:53 UTC, phpengine commented on scripts/upgrade-runtime.sh
> +echo "compiler prerequisites"
Added to commit

2022-07-06 15:54 UTC, phpengine commented on scripts/upgrade-runtime.sh
> +docker tag $( docker image ls | grep 1.57.0 | awk '{ print $3 }' ) t3rn-srtool:1.60.0
Added to commit

2022-07-06 15:54 UTC, phpengine commented on scripts/upgrade-runtime.sh
> +    --image t3rn-srtool:1.60.0 \
Added to commit

2022-07-08 11:06 UTC, chiefbiiko commented
unfortunately, not the fix yet, retested upgrading but hitting same error => coming soon

2022-07-08 11:06 UTC, closed without merging