Fixes Executor
t3rn/t3rn pull request #391
Opened 2022-07-12 08:36 UTC by petscheit

The SideEffect naming has changed, this updates the executor accordingly

2022-07-12 12:43 UTC, chiefbiiko commented on client/executor/index.ts
> +require('dotenv').config()
on purpose?

2022-07-12 12:43 UTC, chiefbiiko submitted a review, later dismissed
LGTM

2022-07-12 13:08 UTC, petscheit commented on client/executor/index.ts
> +require('dotenv').config()
yup, because I work with a local .env file. Shouldn't interfere with anything else

2022-07-12 18:25 UTC, MaciejBaj requested changes

2022-07-12 18:25 UTC, MaciejBaj commented on client/executor/circuit/listener.ts
> +// import "@t3rn/types"
remove

2022-07-29 09:38 UTC, MaciejBaj approved these changes

2022-07-29 09:38 UTC, merged