Utilise the rearchitecture for 3VM and install EVM to the nodes
t3rn/t3rn pull request #400
Opened 2022-07-14 08:25 UTC by AwesomeIbex

## Summary
(Summarize the changes that this pull request creates)-

## Checklist
- [ ] insert any notable changes, in order of commit

## Please check that your PR completes the requirements as follows
- [ ] Tests have been added for bug fixes/features
- [ ] Acceptance criteria from the issue has been completed

## Screenshots (if applicable)

2022-08-11 12:44 UTC, MaciejBaj requested changes

2022-08-11 12:44 UTC, MaciejBaj commented on runtime/standalone/src/contracts_config.rs
> +// impl pallet_evm::Config for Runtime {
Pls add a todo on when planning to resolve it

2022-08-11 12:44 UTC, MaciejBaj commented on primitives/src/account_manager.rs
> +    ) -> Result<u64, sp_runtime::DispatchError>;
What's the returned value here?  extend the docs

2022-08-11 16:21 UTC, AwesomeIbex commented
ci is failing because of XBI but my branch doesn't have the pallet :/ seems like a race condition on CI runner

2022-08-12 08:44 UTC, MaciejBaj approved these changes

2022-08-12 08:45 UTC, merged