Add draft pallet executor staking
t3rn/t3rn pull request #410
Opened 2022-07-26 09:41 UTC by chiefbiiko

## Summary
Checks in the stub pallet treasury and our custom pallet staking. The latter draft is pretty much complete, whereas the former requires substantial implementation still.

## Checklist
- [x] draft pallet staking
- [x] unit test all existing staking functionality

Related #392

2022-07-26 16:27 UTC, MaciejBaj requested changes

2022-07-26 16:27 UTC, MaciejBaj commented on pallets/staking/src/subject_metadata.rs
> +            T::Currency::set_lock(
Should rather be transferring the assets in for executors and marking the lock in pallet staking.

2022-07-26 16:27 UTC, MaciejBaj commented on pallets/staking/src/lib.rs
> +                candidate_stake_count >= state.stake_count,
Ideally should check against min_insurance < bond / total_staked

2022-08-05 13:44 UTC, MaciejBaj submitted a review, later dismissed

2022-08-08 12:07 UTC, alexand3rwilke approved these changes

2022-08-08 14:09 UTC, MaciejBaj approved these changes

2022-08-08 14:09 UTC, merged