docs: add registration part to collator docs
t3rn/t3rn pull request #411
Opened 2022-07-27 19:21 UTC by alexand3rwilke

## Summary
+ Added t0rn faucet
+ Added some necessary steps to register_as_candidate 
+ Changed version to match the latest one

2022-07-28 06:56 UTC, chiefbiiko requested changes
Thanks for elaborating this guide - all my suggestions are just spelling things.

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +1. Go to [polkadot.js](https://polkadot.js.org/apps/#/explorer), switch to t0rn and connect your collator account using polkadot.js
```suggestion
1. Go to the [polkadot.js app](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdev.net.t3rn.io#/accounts) and connect your collator account by clicking "Add account", then inserting your previously generated secret phrase aka mnemonic.
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
>  # Run t3rn Collator on Rococo testnet (t0rn)
```suggestion
# Run a t0rn Testnet Collator
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +2. Set your session keys with your connected collator account under
```suggestion
2. Generate a new session key pair and obtain the corresponding public key. Copy it to your clipboard as it is needed in the next step.
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +Developer/RPC calls/author --> rotateKeys
```suggestion
Developer --> RPC calls --> author --> rotateKeys()
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +## Get some t0rn from faucet
```suggestion
## Get Some T0RN Balance
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +Go to the [t0rn testnet faucet](https://dev.net.t3rn.io/faucet/), insert your substrate address and get some t0rn to cover transaction costs.
```suggestion
Go to the [t0rn testnet faucet](https://dev.net.t3rn.io/faucet/), insert your substrate address and get some T0RN to cover transaction costs.
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +Developer/Extrinsics --> collatorSelection -> registerAsCandidate
```suggestion
Developer --> Extrinsics --> collatorSelection -> registerAsCandidate()
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +Developer/Extrinsics --> session -> setKeys(sr25519_pubkey, 0x1234)
```suggestion
Developer --> Extrinsics --> session -> setKeys(sr25519_pubkey, 0x1234)
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +3. Set the Session Key for your collator under
```suggestion
3. Set the session key for your collator under
```

2022-07-28 06:56 UTC, chiefbiiko commented on docs/t0rn-collator.md
> +This guide outlines the essential minimum of steps required to run a collator for t0rn - a release candidate of t3rn to Rococo testnet. Guide uses the `v1.1.0-rc.0` release to Rococo, please however
```suggestion
This guide outlines the essential minimum of steps required to run a collator for t0rn - a release candidate of t3rn on the Rococo testnet. This guide uses the `v1.1.0-rc.0` release, however always use the latest available version.
```

2022-07-28 15:47 UTC, MaciejBaj submitted a review, later dismissed

2022-07-28 15:47 UTC, MaciejBaj commented
Good to go after resolving @chiefbiiko's points

2022-07-29 16:14 UTC, chiefbiiko approved these changes
LGTM

2022-08-01 09:38 UTC, MaciejBaj approved these changes

2022-08-01 09:38 UTC, merged