Unify side effects
t3rn/t3rn pull request #413
Opened 2022-07-29 07:45 UTC by beqaabu

## Summary
This pr transforms side effects from `LocalTrigger` to regular side effects that the protocol can validate. 

## Checklist
- [ ] insert any notable changes, in order of commit

## Please check that your PR completes the requirements as follows
- [ ] Tests have been added for bug fixes/features
- [ ] Acceptance criteria from the issue has been completed

## Screenshots (if applicable)

2022-08-03 13:28 UTC, AwesomeIbex submitted a review, later dismissed
approved since my review is blocking the pr and I fixed the issues

2022-08-03 15:28 UTC, MaciejBaj requested changes

2022-08-03 15:28 UTC, MaciejBaj commented on pallets/circuit/src/mock.rs
> +            vec![*b"tran", *b"swap", *b"aliq", *b"mult", *b"call"],
re-use from `t3rn_protocol::side_effects::standards::standard_side_effects()`

2022-08-03 15:28 UTC, MaciejBaj commented on primitives/src/match_format.rs
> +pub fn match_side_effect(kind: &StrLike) -> Result<Bytes, &'static str> {
align and cover all cases from `t3rn_protocol::side_effects::standards::standard_side_effects()`

2022-08-03 15:28 UTC, MaciejBaj commented on types/src/side_effect.rs
> +            Action::Transfer => *b"tran",
same, handle cases from `t3rn_protocol::side_effects::standards::standard_side_effects()`

2022-08-04 15:58 UTC, MaciejBaj approved these changes

2022-08-04 15:59 UTC, merged