Use CD to deploy v1.2.0-rc.0 to Rococo
t3rn/t3rn pull request #501
Opened 2022-11-09 10:16 UTC by MaciejBaj

## Summary
Use Github Actions Pipeline to deploy v1.2.0-rc.0 to Rococo

## Checklist
- [ ] insert any notable changes, in order of commit

## Please check that your PR completes the requirements as follows
- [ ] Tests have been added for bug fixes/features
- [ ] Acceptance criteria from the issue has been completed

## Screenshots (if applicable)

2022-11-09 11:01 UTC, chiefbiiko requested changes
We should omit the chain specs and genesis WASM because that must never change.

2022-11-09 11:06 UTC, MaciejBaj commented on runtime/t0rn-parachain/src/lib.rs
> +    transaction_version: 3,
only transaction_version needs bump from v1.1.0-rc.0

2022-11-09 14:07 UTC, chiefbiiko commented on .github/workflows/circuit-t0rn-collator-release.yml
> +    steps:
```suggestion
    steps:
      - name: 🏷️ Get the version tag
        run: echo "PUSHED_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
```

2022-11-10 11:42 UTC, AwesomeIbex commented on .github/workflows/circuit-t0rn-collator-release.yml
> +          ./scripts/upgrade-runtime-unsafe.sh ${{secrets.RUNTIME_UPGRADE_SEED}} wss://dev.net.t3rn.io https://dev.net.t3rn.io/http-rpc ${{env.PUSHED_TAG}} ${UPGRADE_AT_HEIGHT} ${{env.PARACHAIN_NAME}}
This needs password too for ensuresignedby to work, it goes like this `${{secrets.RUNTIME_UPGRADE_SEED}}///${{secrets. RUNTIME_UPGRADE_SEED_PASS}}`

2022-11-11 16:18 UTC, merged