Implemented message signing by registered authorities in Circuit
t3rn/t3rn pull request #54
Opened 2021-07-01 08:26 UTC by zannis

2021-07-05 04:05 UTC, MaciejBaj requested changes

2021-07-05 04:05 UTC, MaciejBaj commented on circuit/src/execution-delivery/src/message_assembly/substrate_gateway_assembly.rs
> +    #[should_panic(expected = "Module with a given name doesn't exist as per the current metadata")]
Runtime logic should never panic!, can u convert it to error throw?

2021-07-05 08:30 UTC, beqaabu approved these changes
Looks good!

2021-07-06 15:35 UTC, MaciejBaj requested changes

2021-07-06 15:35 UTC, MaciejBaj commented on circuit/src/execution-delivery/src/message_assembly/chain_generic_metadata.rs
> +        let _call_found = calls.clone().find(|call| {
remove "_" from var name when used

2021-07-06 17:07 UTC, zannis commented on circuit/src/execution-delivery/src/message_assembly/chain_generic_metadata.rs
> +        let _call_found = calls.clone().find(|call| {
Fixed on following commit.

2021-07-07 15:43 UTC, MaciejBaj commented on circuit/src/execution-delivery/src/message_assembly/substrate_gateway_assembly.rs
> +                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 12, 8, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 9, 9,
👌

2021-07-07 15:44 UTC, MaciejBaj approved these changes

2021-07-07 15:44 UTC, merged