Asset Transaction Payments
t3rn/t3rn pull request #583
Opened 2023-01-17 11:53 UTC by chiefbiiko

# Summary of changes

Allows paying transaction fees using non-native currencies.

Installs [pallet-asset-tx-payment](https://github.com/paritytech/substrate/tree/master/frame/transaction-payment/asset-tx-payment) to the `mock`, `standalone`, and `t0rn` runtime.

Closes [#539](https://github.com/t3rn/t3rn/issues/539)

## Acceptance Checklist

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue):
    - [ ] Have you **written tests **to protect against future occurrences of the bug?
- [x] New feature (non-breaking change which adds functionality)
    - [ ] Have you **seen it working** in a development environment?
    - [x] Have you **written tests** for **happy** and **unhappy** paths?
    - [x] Have you implemented this feature as per the **issue acceptance criteria**?
- [ ] Breaking change (a feature that would cause existing functionality not to work as expected
    - [ ] Is the breaking change **documented**?
    - [ ] Has any previous changes been **deprecated**?
- [ ] CI/CD
    - [ ] If introducing new actions, have you **looked at the action code** for anything spurious?
    - [ ] Have you written **custom scripts** for things that could be actions already on the marketplace?
    - [ ] If introducing new actions, have you **pegged a static version**?
- [ ] Documentation Update
    - [ ] Have you checked other documentation, such as the docs repository?
    - [ ] If updating script documentation, have you **tested it on both environments**?
- [x] Substrate
    - [ ] RPC methods?
    - [ ] Chainspec, both JSON specs & the module?
    - [x] Runtime versioning?
    - [ ] Benchmarks?
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

The `RuntimeVersion.transaction_version` needs to change because the newly introduced treasury pallet index changed.

2023-01-18 10:28 UTC, AwesomeIbex requested changes
Looks good, just some small comments

2023-01-18 10:28 UTC, AwesomeIbex commented on pallets/account-manager/Cargo.toml
> +circuit-runtime-pallets = { path = "../../runtime/common-pallets", default-features = false }
No need for this in `dev-dependencies` as it's used for tests.

2023-01-18 10:28 UTC, AwesomeIbex commented on pallets/account-manager/Cargo.toml
> +  "circuit-runtime-pallets/std",
This would bring in the dev dependency for std when it isn't brought into the binary. Only things in the `dependencies` table should go here.

2023-01-18 10:28 UTC, AwesomeIbex commented on pallets/account-manager/src/tests.rs
> +            // sp_runtime::transaction_validity::TransactionValidityError::Invalid(sp_runtime::transaction_validity::InvalidTransaction::Payment)
comment here

2023-01-18 10:28 UTC, AwesomeIbex commented on runtime/standalone/Cargo.toml
>    "t3rn-primitives/std",
missing pallet-authorship here

2023-01-18 10:28 UTC, AwesomeIbex commented on runtime/standalone/Cargo.toml
> +  # "circuit-runtime-pallets/std",
prolly just remove these comments until we need it since this brings in cumulus and everything that isn't required for standalone

2023-01-19 11:27 UTC, AwesomeIbex approved these changes
Nice one! Happy once ci passes

2023-01-22 20:00 UTC, MaciejBaj approved these changes

2023-01-23 12:20 UTC, AwesomeIbex approved these changes

2023-01-23 12:20 UTC, merged