fix(clock): round info config should be every 400 blocks
t3rn/t3rn pull request #733
Opened 2023-03-14 15:20 UTC by AwesomeIbex

Updates round info to be every 400 blocks. This fixes NewRound spam.

2023-03-14 15:47 UTC, MaciejBaj requested changes
should also work, but RoundInfo in primitives/src/common.rs should be updated/fixed as well. 

right now: 

- term is set to 20 blocks - change to 400
    fn default() -> RoundInfo<B> {
        RoundInfo::new(1u32, 1u32.into(), 20u32.into())
    }
    
- should_update let's triggers "update" each block, so ignores the term requirements 
    /// Check if the round should be updated
    pub fn should_update(&self, now: B) -> bool {
        now - self.head >= self.term
    }

2023-03-15 09:02 UTC, petscheit approved these changes

2023-03-15 11:28 UTC, MaciejBaj commented on pallets/clock/src/lib.rs
> +            if new_round.should_update(n) {
🥇

2023-03-15 11:29 UTC, MaciejBaj approved these changes

2023-03-15 11:32 UTC, merged