Integrate pallet-circuit-execution-delivery into runtime
t3rn/t3rn pull request #74
Opened 2021-08-05 18:18 UTC by beqaabu

In this PR I added `pallet-circuit-execution-delivery` into runtime

2021-08-05 18:57 UTC, MaciejBaj requested changes

2021-08-05 18:57 UTC, MaciejBaj commented on circuit/src/runtime/src/lib.rs
> +            ("Weights", "complex_calculations") => {
Remove for now

2021-08-05 18:57 UTC, MaciejBaj commented on circuit/src/runtime/src/lib.rs
> +// pub type PolkadotLikeGrandpaInstance = pallet_bridge_grandpa::Instance1;
Leve Instance1 of bridge connected

2021-08-05 18:57 UTC, MaciejBaj commented on circuit/src/runtime/src/lib.rs
> +// type Blake2ValU32BridgeInstance = pallet_multi_finality_verifier::Instance1;
Leave 4 active

2021-08-06 07:30 UTC, beqaabu commented on circuit/src/runtime/src/lib.rs
> +            ("Weights", "complex_calculations") => {
fixed in the following commit

2021-08-06 07:31 UTC, beqaabu commented on circuit/src/runtime/src/lib.rs
> +// type Blake2ValU32BridgeInstance = pallet_multi_finality_verifier::Instance1;
fixed in the following commit

2021-08-06 07:31 UTC, beqaabu commented on circuit/src/runtime/src/lib.rs
> +// pub type PolkadotLikeGrandpaInstance = pallet_bridge_grandpa::Instance1;
fixed in the following commit

2021-08-06 11:20 UTC, zannis approved these changes

2021-08-06 13:37 UTC, MaciejBaj approved these changes

2021-08-06 13:37 UTC, merged