refactor: connect and use ReadSFX interface from Circuit to Attesters
t3rn/t3rn pull request #884
Opened 2023-04-25 11:51 UTC by MaciejBaj

# Summary of changes

refactor: connect and use ReadSFX interface from Circuit to Attesters

# Acceptance Checklist

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

## Dependencies

- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any teams which manage the dependencies have been notified of the breaking changes

## Bug (non-breaking change which fixes an issue):

- [ ] Have you **_written tests_** to protect against future occurrences of the bug?

## Feature (non-breaking change which adds functionality)

- [ ] Have you **_seen it working_** in a development environment?
- [ ] Have you **_written tests_** for **_happy_** and **_unhappy_** paths?
- [ ] Have you implemented this feature as per the **_issue acceptance criteria_**?

### Substrate

If this change involves substrate, have you remembered:

- [ ] Storage Migration?
- [ ] RPC methods?
- [ ] Chainspec, both JSON specs & the module?
- [ ] Runtime versioning?
- [ ] Benchmarks?

## Breaking change (a feature that would cause existing functionality not to work as expected)

- [ ] Is the breaking change **_documented_**?
- [ ] Are your commits fully representative of the change?
- [ ] Has any previous functionality been **_deprecated_** and versioned?

## CI/CD

- [ ] If introducing new actions, have you **_looked at the action code_** for anything spurious?
- [ ] Have you written **_custom scripts_** for things that could be actions already on the marketplace?
- [ ] If introducing new actions, have you **_pegged a static version_**?

## Documentation Update

- [ ] Have you checked other documentation, such as the docs repository?
- [ ] If updating script documentation, have you **_tested it on both environments_**?

## Further comments

Feel free to explain in further detail your choices if this is a significant change.

## Screenshots (Please demonstrate this working in PolkadotJS)

2023-05-18 10:22 UTC, AwesomeIbex requested changes
Needs unit testing a lot of various ADTs and clippy lints, please fill in the checklist

2023-05-18 10:22 UTC, AwesomeIbex commented on pallets/circuit/src/lib.rs
> +    impl<T: Config> ReadSFX<T::Hash> for Pallet<T> {
Needs all unhappy path tests, as coverage says

2023-05-18 13:26 UTC, MaciejBaj commented on pallets/circuit/src/lib.rs
> +    impl<T: Config> ReadSFX<T::Hash> for Pallet<T> {
added [ca6690f](https://github.com/t3rn/t3rn/pull/884/commits/ca6690f9974bd4441aca1cd15c23a27551d701cb)

2023-05-19 08:09 UTC, AwesomeIbex approved these changes

2023-05-19 08:32 UTC, merged